[[redirects]]
  from = "/functions/*"
  to = "/functions/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  command = "yarn run build && cd ./functions && npm install && cd ../"
  publish = "build"
  functions = "./functions"

# note: each of these fields are OPTIONAL
[dev]
  command = "yarn start" # Command to start your dev server
  # port = 3000 # Port that the dev server will be listening on
  # functionsPort = 34567 # port for functions server
  targetPort = 3000 # Port of target app server
  publish = "build" # If you use a _redirect file, provide the path to your static content folder
  # jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
  autoLaunch = false # a Boolean value that determines if Netlify Dev launches the local server address in your browser